services:
  app:
    image: node:21-alpine3.18
    working_dir : /app
    tty: true
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - node_module_volume:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_module_volume: